services:

  express-app:
    image: chokchaibiz/express-app
    ports:
      - 8080:8080
    container_name: express-app
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    command: express-app
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock